### ISSUE TITLE
please sync demo/spark-cdk-bundle-add-remove with master

### ISSUE THREAD

**Issue by kwmonroe** [conjure-up/spells#118]
This s/charmhelpers/kv commit is nice:

https://github.com/conjure-up/spells/commit/126f15a4aa602bdb929882f563834a9636d756d8

I have some work for the `demo/spark-cdk-bundle-add-remove` branch that relies on this. Would you please merge the `master` branch into `demo/spark-cdk-bundle-add-remove` so i can PR recent fixes to the demo branch?

**Comment by battlemidget** [comment]
@kwmonroe done, that branch should be synced
