### ISSUE TITLE
openstack novalxd no longer creating neutron networks

### ISSUE THREAD

**Issue by sajoupa** [conjure-up/spells#121]
Hi,

In the openstack-novalxd spell, since commit 04466b468c229a99396b9ec4bb816168ef567959, the part in neutron.sh which creates the networks is commented out.
What's the rationale ?
Maybe I missed something but it looks like a regression, as this spell used to ship the cloud with a couple of networks ready to use.

Thanks.

**Comment by battlemidget** [comment]
Thanks for pointing this out. We are in the middle of transitioning the tools over to work with the newer openstack commands.

**Comment by battlemidget** [comment]
@sajoupa A release is set to go out this week that'll include the neutron fixes. We've got a couple of additional spell updates to make to bigdata and kubernetes which is set to be ready today or tomorrow.
