### ISSUE TITLE
spells with spark fail with lxd/localhost provider

### ISSUE THREAD

**Issue by chrisheckler** [conjure-up/spells#130]
Per https://github.com/juju-solutions/bigtop/issues/52, any spells that deploy spark fail when deployed using the lxd provider.

**Comment by battlemidget** [comment]
Ah this needs an updated lxd profile like what we do with kubernetes and openstack-novlaxd spells

**Comment by battlemidget** [comment]
I'll see if I can look at it tonight

**Comment by chrisheckler** [comment]
fyi, after more testing, I'm thinking it may be zookeeper that is the problem component, not spark.

**Comment by battlemidget** [comment]
Thanks for the additional information, I'll see what I can find

**Comment by chrisheckler** [comment]
@battlemidget @kwmonroe following further investigation I found this in the log https://paste.ubuntu.com/26388694/

Possibly my modem is handing out domains that aren't resolvable.

Here is some insight from inside one of the failing juju deployed containers

```bash
ubuntu@juju-65cf08-1:~$ cat /etc/hostname
juju-65cf08-1
ubuntu@juju-65cf08-1:~$ cat /etc/hosts
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
ubuntu@juju-65cf08-1:~$ hostname
juju-65cf08-1
ubuntu@juju-65cf08-1:~$ hostname -f
hostname: Name or service not known
ubuntu@juju-65cf08-1:~$ 
```

**Comment by jamesbeedy** [comment]
this is https://github.com/juju-solutions/jujubigdata/issues/62

**Comment by kwmonroe** [comment]
Yeah @battlemidget, you can close this out.  It's being tracked in jujubigdata since the underlying problem is with dns in big data clusters.
