### ISSUE TITLE
canonical-kubernetes 02_get-kubectl fails to setup kubectl if $HOME/bin not in PATH

### ISSUE THREAD

**Issue by mthaddon** [conjure-up/spells#138]
If $HOME/bin is not in PATH, a user won't have the custom $HOME/bin/kubectl wrapper so they won't be able to connect to the cluster correctly.

**Comment by battlemidget** [comment]
This has been addressed, https://github.com/conjure-up/spells/pull/183, some in here https://github.com/conjure-up/spells/pull/179,
