### ISSUE TITLE
openstacknova-lxd does not allow for deploying using an existing bridge and external dhcp

### ISSUE THREAD

**Issue by raema** [conjure-up/spells#142]
When selecting an existing bridge during deployment of openstacknova-lxd, the deployment is unsuccessful.

1. The lxc profile juju-controller is created, but it is not bridged to the existing bridge. Instead the controller gets an ip from the conjure0 network.

sudo lxc list
[sudo] password for ubuntu:
If this is your first time using LXD, you should also run: lxd init
To start your first container, try: lxc launch ubuntu:16.04

+----------------+---------+--------------------+------+------------+-----------+
|      NAME      |  STATE  |        IPV4        | IPV6 |    TYPE    | SNAPSHOTS |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-0  | RUNNING | 10.20.0.104 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-1  | RUNNING | 10.20.0.140 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-10 | RUNNING | 10.20.0.185 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-11 | RUNNING | 10.20.0.183 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-12 | RUNNING | 10.20.0.184 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-13 | RUNNING | 10.20.0.189 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-14 | RUNNING | 10.20.0.123 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-15 | RUNNING | 10.20.0.148 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-2  | RUNNING | 10.20.0.153 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-3  | RUNNING | 10.20.0.107 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-4  | RUNNING | 10.20.0.149 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-5  | RUNNING | 10.20.0.170 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-6  | RUNNING | 10.20.0.150 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-7  | RUNNING | 10.20.0.156 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-8  | RUNNING | 10.20.0.199 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-8d1353-9  | RUNNING | 10.20.0.200 (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+
| juju-f8e20b-0  | RUNNING | **10.10.8.117** (eth0) |      | PERSISTENT | 0         |
+----------------+---------+--------------------+------+------------+-----------+

In order to move the juju-controller to bridge0 we can use 'lxc profile edit juju-controller' to add eth0 bridged to bridge0

sudo lxc profile show juju-controller
config:
  boot.autostart: "true"
  security.nesting: "true"
description: ""
**devices:
  eth0:
    nictype: bridged
    parent: bridge0
    type: nic
  eth1:
    nictype: bridged
    parent: conjureup0
    type: nic**
name: juju-controller

2. Instances are not able to reach the external network on bridge0.

* Add a interface to the neutron-gateway container connected to bridge0

sudo lxc network attach bridge0 juju-d511cb-2 eth2

* set neutron-gateway to use the interface on bridge0 as the external network

juju config neutron-gateway ext-port=eth2

* Create ext_net_subnet so that it included the subnet on bridge0 and a range for floating ips not used by lxd

**Comment by ryan-beisner** [comment]
I understand the use case, and agree that could be a useful mode to add in the future.  However, the request is outside the current scope of the the all-in-one spell:  that it is a contained, single-machine deployment for developing in or developing against OpenStack in a simulated private cloud.

For use cases where connectivity from a corporate LAN/WAN to the instances in the cloud is necessary, a multi-node MAAS-based OpenStack deployment is recommended.

Alternatively, you can customize the more advanced (and less automated) developer deploy process as documented in our upstream charms project.

https://docs.openstack.org/charm-guide/latest/openstack-on-lxd.html

See also:
https://www.ubuntu.com/openstack/install
https://docs.openstack.org/charm-guide/latest
