### ISSUE TITLE
Creating a storageclass and making it default, does not work as a default storageclass with canonical-kuberenetes spell

### ISSUE THREAD

**Issue by shrajfr12** [conjure-up/spells#158]
As an alternative to issue #153, if we create in addon script a storageclass and make sure it shows up as default, the defaultness does not work when pv claims are created without specifying storageclass name.

For e.g create a storage class from a file sc.yaml
===
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug
===
%> kubectl create -f sc.yaml
%> kubectl get storageclass
NAME                 PROVISIONER             AGE
standard (default)   kubernetes.io/aws-ebs   1h

If you create claim using  test.yaml with the following text
==
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
===
%>kubectl create -f test.yaml
%>kubectl get pvc myclaim
NAME      STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
myclaim   Pending
%> kubectl describe pvc myclaim shows the following event

Normal  FailedBinding  3m (x208 over 53m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set

Per documentation, if no storageclass is set, then the default storageclass should get used and that is not what we observe. (If we add the storageClassName: standard, then of course the pv gets bound automatically, but then we did not use the default storage class in that case)

conjure-up version is 2.5.5. 
cloud: aws

**Comment by Cynerva** [comment]
Thanks for the report @shrajfr12. In agreement with your observations on Slack, this is almost certainly because DefaultStorageClass is missing from the default set of admission controllers in CDK deploments.

Since this is a bug in the charms, I've created an issue over at https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/517 to track it.

**Comment by battlemidget** [comment]
Closing this one out, thanks @Cynerva
