### ISSUE TITLE
openstack-base: openstack instances not getting ip's

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/spells#16]
This may not be the proper project to post this in. After creating an openstack on MAAS with conjure-up when I create new instances inside of openstack, horizon shows an ip associated with it however when I login through the web console to the machine there is not an IP. The interface is configured as DHCP on the instance.

I ran juju config neutron-openvswitch enable-local-dhcp-and-metadata=true to enable the dhcp server but that didn't seem to work

It looks like the conjurup0 bridge isn't attached to an interface

```
brctl show
bridge name bridge id STP enabled interfaces
conjureup0 8000.000000000000 no
```

And that has the IP of the ext-net 10.99.0.1

Original: https://github.com/conjure-up/conjure-up/issues/494

**Comment by hydra1983** [comment]
I'm struggling with this now. :(

**Comment by ryan-beisner** [comment]
We believe this is resolved, based on current testing. If you find that is not the case, please re-open the issue. Thank you.
