### ISSUE TITLE
openstacknova-lxd: Unknown configuration key "lxc.aa_profile"

### ISSUE THREAD

**Issue by mpesari** [conjure-up/spells#171]
I'm trying to conjure-up an Openstack installation on LXD 3.0, but I get this error:

```
# cat /var/snap/lxd/common/lxd/logs/juju-6ba489-0/lxc.log 
lxc 20180406135927.324 ERROR    lxc_confile - confile.c:parse_line:2340 - Unknown configuration key "lxc.aa_profile"
lxc 20180406135927.324 ERROR    lxc_parse - parse.c:lxc_file_for_each_line_mmap:102 - Failed to parse config: lxc.aa_profile=unconfined
```

Looking at other files in this project I can see an lxc version check and configuration key change was added in #166. Maybe adding this would fix my problem. Thanks for checking it out!

**Comment by battlemidget** [comment]
Ah! I didn't do openstack just kubernetes. Sorry about that, I'll get a fix pushed out asap

**Comment by battlemidget** [comment]
Fixed with https://github.com/conjure-up/spells/commit/b95cd1e9c4d600e3e7ae542b0dc263edf271df88

I'll push builds out now
