### ISSUE TITLE
openstack-base: No list of flavors available.

### ISSUE THREAD

**Issue by neith00** [conjure-up/spells#18]
After a fresh install of Openstack using conjure-up.
The list of predefined flavors is empty.

juju 2.0.0-xenial-amd64
conjure-up 2.0.2

**Comment by ryan-beisner** [comment]
As of OpenStack Newton upstream, there are no default nova flavors.  Cloud admins are expected to create flavors.

**Comment by battlemidget** [comment]
Thanks good to know, I'll add this to our documentation
