### ISSUE TITLE
intall_helm function does not use  getkey "kubectl.dest" so it assumes kubectl is always in PATH

### ISSUE THREAD

**Issue by shrajfr12** [conjure-up/spells#184]
With the recent refactoring due to removing KUBECONFIG, kubectl script in $HOME/bin is no longer gettting created and hence direct reference to kubectl without a path prefix or getting it from "kubectl.dest" can result in "command not found" type errors.

**Comment by Cynerva** [comment]
Thanks for alerting us to this.

PR: https://github.com/conjure-up/spells/pull/183

**Comment by battlemidget** [comment]
Fixed
