### ISSUE TITLE
openstack-novalxd: keystone.sh: key pair not uploaded to nova.

### ISSUE THREAD

**Issue by hmlanigan** [conjure-up/spells#19]
It appears that keystone.sh assumes that the username running conjure-up is ubuntu, e.g. the same as the user in the nova-compute unit.  If they are different, the key pair isn't uploaded.

ubuntu@juju-0a0c8d-12:~$ tail keypair.sh
...
export SSHPUBLICKEY=/home/ubuntu1-admin/.ssh/id_rsa.pub
if ! openstack keypair show ubuntu-keypair > /dev/null 2>&1; then
    debug "adding ssh keypair from $SSHPUBLICKEY"
    openstack keypair create --public-key $SSHPUBLICKEY ubuntu-keypair > /dev/null 2>&1
fi
exposeResult "SSH Keypair is now imported and accessible when creating compute nodes." 0 "true"
ubuntu@juju-0a0c8d-12:~$ nova keypair-list
+------+-------------+
| Name | Fingerprint |
+------+-------------+
+------+-------------+
ubuntu@juju-0a0c8d-12:~$ ls /home/ubuntu/.ssh
authorized_keys  id_rsa  id_rsa.pub
ubuntu@juju-0a0c8d-12:~$

**Comment by battlemidget** [comment]
Did you try setting the right path during the post processing questions?

https://github.com/conjure-up/spells/blob/master/openstack-novalxd/steps/step-03_keypair.yaml#L10

You can point it to a different default

**Comment by hmlanigan** [comment]
I’m not sure that would solve the problem.  There is no ubuntu user on the base operating system.  Where would the newly created key go?

I can give it a try the next time I run conjure-up openstack-novalxd.

-heather

On Oct 24, 2016, at 2:46 PM, Adam Stokes <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you try setting the right path during the post processing questions?

https://github.com/conjure-up/spells/blob/master/openstack-novalxd/steps/step-03_keypair.yaml#L10

You can point it to a different default

**Comment by hmlanigan** [comment]
I changed the ssh key location to /home/ubuntu/.ssh/id_rsa.pub during the configuration phase.  This time the .ssh keys weren't uploaded to the nova-cloud-controller unit and the keypair.sh script was still trying to use the user home dir.

from keypair.sh: 
export SSHPUBLICKEY=/home/ubuntu1-admin/.ssh/id_rsa.pub
if ! openstack keypair show ubuntu-keypair > /dev/null 2>&1; then
    debug "adding ssh keypair from $SSHPUBLICKEY"
    openstack keypair create --public-key $SSHPUBLICKEY ubuntu-keypair > /dev/null 2>&1
fi
exposeResult "SSH Keypair is now imported and accessible when creating compute nodes." 0 "true"

ubuntu@juju-5409e6-12:~$ ls .ssh
authorized_keys

**Comment by battlemidget** [comment]
Thanks I'll look into this

**Comment by hmlanigan** [comment]
one more bit of info: 

ubuntu1-admin@ubuntu1:~/.cache/conjure-up/openstack-novalxd/steps$ cat step-03_keypair.err
Connection to 10.139.193.101 closed.
ERROR exit status 1 (/home/ubuntu/.ssh/id_rsa*: No such file or directory)
Connection to 10.139.193.101 closed.

**Comment by ryan-beisner** [comment]
We've run several deployments with the current snap, and keys are successfully imported.  Please re-raise this issue if it is observed.
