### ISSUE TITLE
Empty GITHUB_TOKEN in kubeflow addon crashes deployment

### ISSUE THREAD

**Issue by ktsakalozos** [conjure-up/spells#192]
If a user does not provide a GITHUB_TOKEN the kubeflow step fails. ks init at https://github.com/conjure-up/spells/blob/master/canonical-kubernetes/addons/kubeflow/steps/02_install-kubeflow/after-deploy#L14 fails with `ERROR GET https://api.github.com/repos/ksonnet/parts/commits/master: 401 Bad credentials []`.

Here is a full run of the after deploy script:
```
+ . /home/jackal/workspace/charms/spells//sdk/common.sh
+ KUBECTL=/snap/bin/kubectl
+ export GITHUB_TOKEN=None
+ GITHUB_TOKEN=None
+ export JUJU_MODEL=conjure-canonical-kubern-6e7
+ JUJU_MODEL=conjure-canonical-kubern-6e7
+ mkdir -p /home/jackal/.local/share/kubeflow
+ cd /home/jackal/.local/share/kubeflow
+ ks -v init kubeflow.conjure-canonical-kubern-6e7
INFO  Using context 'conjure-canonical-kubern-6e7' from the kubeconfig file specified at the environment variable $KUBECONFIG
DEBUG Failed to open swagger at https://34.219.108.130:443/swagger.json
Get https://34.219.108.130:443/swagger.json: x509: certificate signed by unknown authority
ERROR GET https://api.github.com/repos/ksonnet/parts/commits/master: 401 Bad credentials []
```

Note that GITHUB_TOKEN is set to _None_ 

I think we have two options here, either 
 - mark the GITHUB_TOKEN required at  https://github.com/conjure-up/spells/blob/master/canonical-kubernetes/addons/kubeflow/steps/02_install-kubeflow/metadata.yaml#L4 , or
 - do not expose GITHUB_TOKEN if we detect it is set to None.

@hyperbolic2346, what do you think? Is GITHUB_TOKEN required? I remember there was a quota limit that made Kubeflow installation impractical without GITHUB_TOKEN. Is this the case?

**Comment by hyperbolic2346** [comment]
@ktsakalozos I ran into API rate limits when I didn't have a token and the install would fail. That is why I added it. We can try to go with not exposing the key, but I think you will hit that rate limit and the delay is 1 hour.

**Comment by carmine** [comment]
Given that the rate limit could happen, at the least we should expose that information during the install process.  Could add something like "**(strongly recommended)**". And give a reason / explanation for why.

Requiring the TOKEN would increase friction a bit; so I'd prefer to not require it; and adjust the script so that it doesn't fall over.

**Comment by hyperbolic2346** [comment]
@battlemidget only due to my dedication to correctness.
