### ISSUE TITLE
need better description for microk8s

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/spells#196]
https://github.com/conjure-up/spells/blob/master/spells-index.yaml#L37

@Cynerva @kwmonroe @ktsakalozos 

Can you guys help me out with this?

**Comment by kwmonroe** [comment]
How about we lift the tag line from https://microk8s.io/:
```
Designed for developing Kubernetes workloads locally.
```

I'd also be ok with stealing the k8s-core description and tweaking it for microk8s:
```
This is a minimal Kubernetes cluster with intended usage being small, local deployments for testing and development.
```
