### ISSUE TITLE
NovaLXD networks not created

### ISSUE THREAD

**Issue by clauded** [conjure-up/spells#208]
Deploying Openstack-novalxd with conjure-up on ubuntu 18.04.1. Openstack is installed ok (everything looks ok when running "juju status" and access to Horizon is working) but default Openstack networks are not created as neutron.sh fails to authenticate to keystone.

In neutron.log:

keystoneauth1.exceptions.http.NotFound: (http://10.0.8.163:5000/v3/tokens): The resource could not be found. (HTTP 404) (Request-ID: req-50ae2327-8395-4d55-b696-0752f966d020)
Traceback (most recent call last):
  File "./neutron-tenant-net", line 70, in <module>
    region_name=os.environ['OS_REGION_NAME'])
  File "/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 176, in __init__
    self.authenticate()
  File "/usr/lib/python2.7/dist-packages/keystoneclient/httpclient.py", line 578, in authenticate
    resp = self.get_raw_token_from_identity_service(**kwargs)
  File "/usr/lib/python2.7/dist-packages/keystoneclient/v2_0/client.py", line 220, in get_raw_token_from_identity_service
    _("Authorization Failed: %s") % e)
keystoneauth1.exceptions.auth.AuthorizationFailure: Authorization Failed: (http://10.0.8.163:5000/v3/tokens): The resource could not be found. (HTTP 404) (Request-ID: req-e8f409be-9291-4654-bcbe-abd570f94d43)

**Comment by ryan-beisner** [comment]
We've moved beyond that error with the latest snap release of conjure-up.  There is a separate failure (race condition) which I'll be raising and linking here.

Safe to close this specific issue as resolved.

**Comment by ryan-beisner** [comment]
Please see:  https://github.com/conjure-up/spells/issues/222

**Comment by ryan-beisner** [comment]
FTR, this was a keystone v2, v3 issue.
