### ISSUE TITLE
Upgrade Prometheus to version 2.X+

### ISSUE THREAD

**Issue by CalvinHartwell** [conjure-up/spells#231]
Hi all,

Can we please upgrade Prometheus to version 2.X+ for the k8s spells? 

Right now I don't see any problems when using 2.X over 1.X and this is already defacto for bootstack/fce etc. 

Cheers

**Comment by kwmonroe** [comment]
We switched to prom2 in https://github.com/conjure-up/spells/pull/224

**Comment by CalvinHartwell** [comment]
Oh nice, I didn't see this - thanks!
