### ISSUE TITLE
update addons-aliases for charmed-k8s

### ISSUE THREAD

**Issue by kwmonroe** [conjure-up/spells#247]
With the recent change in https://github.com/conjure-up/spells/pull/246, `canonical-kubernetes` is now `charmed-kubernetes`.

We should update `addons-aliases.yaml` to match:

https://github.com/conjure-up/spells/blob/master/addons-aliases.yaml

FWIW, nothing is broken today because of our symlinks from canonical->charmed, but if those links go away in the future, shortcuts like `conjure-up prometheus` will fail.

**Comment by joedborg** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rename Canonical to Charmed in spell addons](https://trello.com/c/tsRmrwpj/1148-rename-canonical-to-charmed-in-spell-addons)

**Comment by joedborg** [comment]
Merged https://github.com/conjure-up/spells/pull/248
