### ISSUE TITLE
non-integer constraints not handled correctly for add-machines API

### ISSUE THREAD

**Issue by arosales** [conjure-up/spells#45]
It seems with the new 00_deploy-done code the spell is not waiting for the deploy to complete. In recent testing as soon as I select to deploy application the spell almost immediately goes to the final ganglia test which errors in the following stack trace:

```
... mmcc trimmed red herring error message
```

The deployment usually takes about 10 minutes in AWS. The spell is only waiting < 1 minute before going to the final ganglia step. Thus, I don't think we are waiting for the applications to be become active.

-thanks,
Antonio

**Comment by battlemidget** [comment]
This is the culprit:

```
http://paste.ubuntu.com/23948430/
```

The constraints aren't being parsed propery for juju to handle. working through this now

**Comment by mikemccracken** [comment]
moved to https://github.com/conjure-up/conjure-up/issues/654

**Comment by arosales** [comment]
Thanks for the quick work on this. Do you know when this will be in the beta channel as docs have 

` snap install conjure-up --classic --beta
`

and this is pretty prevalent?

**Comment by battlemidget** [comment]
I've got a couple more tests to run and then I'll push to beta today

**Comment by battlemidget** [comment]
The current beta works it just doesn't process the constraints
