### ISSUE TITLE
embed bundles in spells

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/spells#49]
I think we want to lock revisions for charms and embed those bundles directly into the spells. We'd need a automated way to do so, this bug is for getting that addressed.

**Comment by javacruft** [comment]
+1 this will avoid breaks during charm releases where behaviour or configuration options change for new deployments (to be clear, charm upgrades will always work)

**Comment by battlemidget** [comment]
conjure-up now supports the --channel flag and I think is a nice compromise of still relying on a stable release in the charmstore without the need of embedding bundles directly in the spell.
