### ISSUE TITLE
k8s: support for privileged containers

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/spells#52]
Need a way to enable `--allow-privileged` for kubelet. This probably should be in the `kubernetes` charms config, though we could easily make this a step to update the configuration options now.

**Comment by bigjools** [comment]
\o/ Thanks :)

**Comment by battlemidget** [comment]
Spoke with the container guys and a charm config option is on the roadmap for kubernetes 1.6.0 release. Once that's done we can look into providing a additional step to walk a user through enabling that option

**Comment by marcoceppi** [comment]
That field has landed and is in candidate for the 1.6 release.

In the future, lets make sure conjure-up isn't doing out of band updates to kuberntes and use the charms as a conduit.

**Comment by battlemidget** [comment]
Is this accessible through the "advanced config" screen? Or is this something we want to whitelist so that it's always shown to the user?

**Comment by marcoceppi** [comment]
I think whitelisting is worth it. There's probably a few other
configuration options we want to whitelist.

This is the config field on worker, btw. Master should remain auto

**Comment by battlemidget** [comment]
Ok thanks

**Comment by battlemidget** [comment]
Added here https://github.com/conjure-up/spells/commit/1d320bf44b752b1e2e4cf6ba2279dd385776fdd9, once 1.6.x comes out of the charmstore this will be available

**Comment by marcoceppi** [comment]
This should only be a whitelist for the worker. The default of 'auto' on
master should be sufficient

**Comment by battlemidget** [comment]
@marcoceppi thanks ill fix that
