### ISSUE TITLE
kubernetes-core & canonical-kubernetes assume default LXD storage pool name

### ISSUE THREAD

**Issue by mjs** [conjure-up/spells#58]
The LXD profile installed by the kubernetes-core and canonical-kubernetes spells assume a pool name of "default" for the root device. This is fine if you've used the default pool name suggested by `lxd init` but causes all LXD instances to fail to come up otherwise. The errors emitted are fairly cryptic and it took me a fair bit of debugging to figure out what happened.

Can the `profile` field be left out so that LXD will just use the right value? Alternatively, can conjure-up ask LXD for the storage pool name (perhaps by looking at the default profile?) and put that into the profile it sets?

**Comment by battlemidget** [comment]
We are going to use our own storage pool to keep things simple, fixed in https://github.com/conjure-up/spells/commit/500f8c6497a26e45084b55665520abc8cd6232bb
