### ISSUE TITLE
openstack-novalxd: Pike support

### ISSUE THREAD

**Issue by battlemidget** [conjure-up/spells#62]
The following code snippet from Robert Ayres needs to be modified to work with our openstack-novalxd spell:

```
#!/bin/sh -e

DEBIAN_FRONTEND=noninteractive sudo apt-get -qy -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install python-openstackclient < /dev/null

. ~/admin-openrc

# create ubuntu user
openstack project create --description "Created by Juju" ubuntu
openstack user create --project ubuntu --password password --email juju@localhost ubuntu

# add tiny flavor
openstack flavor create --id 1 --ram 512 --disk 8 --vcpus 1 m1.tiny

# configure external network
openstack network create --external ext-net
openstack subnet create --subnet-range 192.168.122.0/24 --no-dhcp --gateway 192.168.122.1 --network ext-net --allocation-pool start=192.168.122.200,end=192.168.122.254 ext-subnet

# create vm network
openstack network create --project ubuntu ubuntu-net
openstack subnet create --project ubuntu --subnet-range 10.0.5.0/24 --gateway 10.0.5.1 --network ubuntu-net --dns-nameserver 192.168.122.1 ubuntu-subnet
openstack router create --project ubuntu ubuntu-router
openstack router add subnet ubuntu-router ubuntu-subnet
openstack router set --external-gateway ext-net ubuntu-router

# create pool of floating ips
i=0
while [ $i -ne 10 ]; do
	openstack floating ip create ext-net
	i=$((i + 1))
done

. ~/ubuntu-openrc

# configure security groups
openstack security group rule create --protocol icmp --ingress --ethertype IPv4 default
openstack security group rule create --dst-port 22 --protocol tcp --ingress --ethertype IPv4 default

# import key pair
openstack keypair create --public-key id_rsa.pub ubuntu-keypair
```

@falfaro pinging you on this incase you'd like to take another stab at getting our spell ready for Ocata?

**Comment by battlemidget** [comment]
https://trello.com/c/Wb32TfdO/80-3-update-openstack-spells-to-work-with-latest-pike-release

**Comment by falfaro** [comment]
Willing to test this change but I'm not sure how to specify Ocata when running on Xenial. Mind giving me a hint?

**Comment by falfaro** [comment]
Ocata or Pike, I meant :-)

**Comment by battlemidget** [comment]
So Pike is enabled by default, you would have to go into each charm's configuration in the application configuration screen to choose other versions

**Comment by battlemidget** [comment]
https://github.com/conjure-up/spells/commit/0a309c061299e60475dec07ff76d26f13f6078c9

**Comment by falfaro** [comment]
Is it there a way to automate selecting Pike instead of whatever the default is (e.g. Mitaka)?

**Comment by battlemidget** [comment]
What do you mean? Pike is the default

**Comment by falfaro** [comment]
Is it there a way to automate selecting Pike instead of whatever the default is (e.g. Mitaka)?

**Comment by falfaro** [comment]
I thought that on Xenial the default was to deploy Mitaka.

**Comment by battlemidget** [comment]
The charms and bundles have been updated to use Pike and that includes on Xenial

**Comment by battlemidget** [comment]
@falfaro my mistake you are right we need to make some additional changes to make this work for Pike, ill update the bug when i got some steps written down

**Comment by battlemidget** [comment]
Completed, this will be available in an upcoming stable release
