### ISSUE TITLE
landscape: spell doesn't register machines/containers of the landscape deploy into the landscape that's running

### ISSUE THREAD

**Issue by mitechie** [conjure-up/spells#63]
It'd be awesome for the out of the box experience if the machines that landscape runs was also managed so that you can see them in machines and look for immediate out of date packages and the like.

**Comment by battlemidget** [comment]
Going to file a bug here https://launchpad.net/landscape-bundles as a wishlist item for landscape to handle (per david britton)

**Comment by battlemidget** [comment]
Bug filed https://bugs.launchpad.net/landscape-bundles/+bug/1681837, closing this one out and will coordinate any changes needed with the spell

**Comment by battlemidget** [comment]
Going to work on some post processing to handle this for now.

**Comment by battlemidget** [comment]
Autopilot is going away, closing this issue out
