### ISSUE TITLE
openstack-base:18 machines deployed for 4 machine bundle

### ISSUE THREAD

**Issue by jogeo** [conjure-up/spells#67]
Selecting openstack-base results in 18 machines being requested from MAAS, rather than the 4 expected. Please see attached logs.

Juju: 2.1.2-xenial-ppc64el

MAAS: 2.1.3+bzr5573-0ubuntu1 (16.04.1)

$ snap info conjure-up
name:      conjure-up
summary:   "Package runtime for conjure-up spells"
publisher: canonical
contact:   https://github.com/conjure-up/conjure-up
description: |
  This package provides conjure-up, an interface to installing spells that
  provide the user with an end to end walkthrough experience for installing and
  using big software.
  
commands:
  - conjure-up.conjure-down (conjure-down)
  - conjure-up
  - conjure-up.juju (juju)
tracking:  beta
installed: 2.2-beta3 (232) 94MB classic
refreshed: 2017-04-28 19:14:02 +0000 UTC
channels:                          
  beta:    2.2-beta3         (232) 94MB classic
  edge:    2.2-beta3+cef5df9 (238) 89MB classic

**Comment by jogeo** [comment]
[conjure-up.zip](https://github.com/conjure-up/spells/files/966092/conjure-up.zip)

**Comment by jogeo** [comment]
[juju-status.txt](https://github.com/conjure-up/spells/files/966094/juju-status.txt)

**Comment by battlemidget** [comment]
Did this start happening when switched to beta?

**Comment by jogeo** [comment]
Yes stable works as expected but beta has this issue. I reproduced on x86 as well.

**Comment by battlemidget** [comment]
@jogeo thanks we'll work to get this fixed

**Comment by battlemidget** [comment]
@jogeo please subscribe to the above bug, im going to close this one out
