### ISSUE TITLE
Too many open files on lxd after some days

### ISSUE THREAD

**Issue by ktsakalozos** [conjure-up/spells#72]
As reported by @madeden leaving an lxd deployment on for long periods of time (more than 1 month in his case) may result to the follwoing error:  https://github.com/lxc/lxd/issues/2252

**Comment by battlemidget** [comment]
What's his `/etc/sysctl.conf` look like on the host?

**Comment by ktsakalozos** [comment]
As @battlemidget pointed out we already set the respective limits. So the error reported by @madaden has to do with a deployment on LXD that did not involve conjureup. Closing this as invalid.
