### ISSUE TITLE
openstack-novalxd update ip addr selection for ext-subnet

### ISSUE THREAD

**Issue by hmlanigan** [conjure-up/spells#76]
With recent changes to conjure-up, neither network bridge is using 10.99.0.0/24 therefore deployed openstack instances are reachable.  I had to manually remove the ext-net and create a new to work with the conjureup0 bridge. 

(I picked the bridge not being used by the containers deployed for the openstack)

Most noticeable when doing a juju bootstrap against a conjured-up openstack.

**Comment by battlemidget** [comment]
Yea we need to fix that, need to add the option in the post processing steps to assign correct networks

**Comment by battlemidget** [comment]
This has been addressed in candidate channel, please test against that and let us know if there are any issues
