### ISSUE TITLE
juju wait command in conjure-up 2.2.2 doesn't support retry argument 

### ISSUE THREAD

**Issue by samantha-jp** [conjure-up/spells#84]
$ snap list
Name        Version     Rev   Developer  Notes
conjure-up  2.2.2       549   canonical  classic
core        16-2.26.14  2462  canonical  -
$ whereis juju
juju: /snap/bin/juju

$ cat 00_deploy-done.err
+ . /home/samantha_jian/spell/spells/sdk/common.sh
+ retry_arg=-r5
+ [[ '' == \t\e\s\t ]]
+ juju wait -r5 -vwm conjure-up-localhost-95a:conjure-openstack-base-b3a
usage: juju-wait [-h] [-e MODEL] [--description] [-q] [-v] [-w] [-t MAX_WAIT]
                 [--version]
juju-wait: error: unrecognized arguments: -r5
+ setResult 'Applications did not start successfully'
+ redis-cli set conjure-up.openstack-base.00_deploy-done.result 'Applications did not start successfully'
+ local conjure_redis_cli
+ local system_redis_cli
+ local cli
++ which conjure-up.redis-cli
+ conjure_redis_cli=/snap/bin/conjure-up.redis-cli
++ which redis-cli
+ system_redis_cli=/snap/conjure-up/549/bin/redis-cli
+ '[' /snap/bin/conjure-up.redis-cli = /snap/bin/conjure-up.redis-cli ']'
+ cli=/snap/bin/conjure-up.redis-cli
+ /snap/bin/conjure-up.redis-cli set conjure-up.openstack-base.00_deploy-done.result 'Applications did not start su
ccessfully'
+ exit 1
$

The deployment goes successfully after passing no -r to the juju wait command in 00_deploy-done script.

**Comment by battlemidget** [comment]
Yea you'll want to use conjure-up from edge for your spell. That includes the right juju wait plugin

**Comment by battlemidget** [comment]
conjure-up is in candidate and going through the review process. If you want, please test against candidate and if problem persists feel free to reopen this bug
